### ISSUE TITLE
你好！群发消息写在哪里了呀？

### ISSUE THREAD

**Issue by yumianhuli2** [jzyong/game-server#50]
你好！群发消息写在哪里了呀？谢谢哈！

**Comment by jzyong** [comment]
可参考broadcastFishEnter.broadcastFishEnter

**Comment by yumianhuli2** [comment]
> 可参考broadcastFishEnter.broadcastFishEnter

我是指netty有广播某个客户端pos通过服务器给其他客户端的例子吗？谢谢哈！
